# Initial data cleaning
# Nov 2025
# ---------------
# Load libraries
# ---------------
library(tidyverse)
library(janitor)

# ------------------
# Read in the data
# ------------------
# Read in raw data
rawdata <- read_csv("raw-data/BES-data-code-hackathon-raw-outputs.csv")

# Exclude 127 rows from test run prior to 12 noon 30th Sept
rawdata <- 
  rawdata %>%
  slice(-(1:127))

# Rename columns to make them easier to deal with
raw_data_all <-
  rawdata %>%
  dplyr::select(paper_number = `1. Paper number`,
                doi = `2. DOI of paper (please copy paste to avoid errors)`,
                year_published = `3. Year of publication (on spreadsheet)`,
                journal = `4. Journal  (on spreadsheet)`,                                                                                                                                                                                                                                                                              
                article_type = `5. Article type  (on spreadsheet)`,                                                                                                                                                                                                                                                                         
                data_used = `7. Does the paper have data?`, 
                data_availability = `1. Are the data mentioned in the Data Availability statement?`,  
                data_availability_text = `6. Please paste the text of the Data Availability statement here`, 
                data_link = `2. Are you able to find the data using the link/instructions in the Data Availability statement?`,                                                                                                                                                                                                          
                data_archive =  `3. Where are the data archived?`,     
                data_doi = `4. Does the dataset have a DOI?`,
                data_license = `11. Does the data have a license?`,                                                                                                                                                                                                                                                                         
                data_license_type = `12. If yes, what license?`,    
                data_download = `5. Can you download the data?`,                                                                                                                                                                                                                                                                             
                data_open = `6. Can you open the data?`,                                                                                                                                                                                                                                                                                
                data_format = `7. What format are the data in?`,                                                                                                                                                                                                                                                                           
                data_README = `8. Does the data have a README/metadata?`,                                                                                                                                                                                                                                                                  
                data_README_scale = `9. How useful is the README/metadata? Read the notes in the protocol to help with decisions here. SKIP THIS Q IF NO README EXISTS.` , 
                data_completeness = `10. How complete is the archived data?`,  
                data_cited = `13. Has the data been cited (excluding the original paper it was archived for)? You can find this information on the Dryad and Figshare landing pages for the dataset on the right hand side. For other repositories it varies. If you can't find out easily just pick Unsure.`,                           
                data_citations = `14. If yes, how many times?  Enter number or Unclear`,                                                                                                                                                                                                                                                      
                data_cited_notself = `15. Has the data been cited by someone other than the original authors? You can find this by clicking on the citations and looking at the papers that cite the data.`,                                                                                                                                      
                data_citations_notself = `16. If yes, how many times? (excluding the original paper it was archived for) Enter number or Unclear`,
                code_used = `0.1 Does the paper use code?`,
                code_alert = `0.2 If the paper uses code, and this is NOT archived (i.e. they mention using R or Python but don't provide any scripts) please copy-paste the text from the paper that alerted you to them using code...`,                                                                                                 
                code_archived = `0.3 Does the paper have archived code?`,
                code_availability = `1. Is the code archiving described in the Data Availability (or equivalent) statement?`,   
                code_link =  `2. Are you able to find the code using the link/instructions in the Data Availability (or equivalent) statement?`,                                                                                                                                                                                          
                code_archive = `3. Where are the code archived?`,
                code_doi = `4. Does the code have a DOI?`,
                code_license = `16. Does the code have a license?`,                                                                                                                                                                                                                                                                        
                code_license_type =  `17. If yes, what license?`,  
                code_CITATION = `15. Does the code have a CITATION file?`, 
                code_download = `5. Can you download the code?`,                                                                                                                                                                                                                                                                            
                code_open = `6. Can you open the code?`,                                                                                                                                                                                                                                                                              
                code_format = `8. What format is the code in?`,
                code_language = `7. What language is the code written in?`,
                code_README = `9. Does the code have a README?`, 
                code_README_scale = `10. How useful is the README? See the protocol for help with making decisions about this. SKIP THIS Q IF NO README EXISTS.`,
                code_annotation_scale = `11. How well is the code annotated? See the protocol for help with making decisions about this.`,                                                                                                                                                                                                           
                code_vignette = `12. Does the code have a separate vignette with examples of how the code should be used?`,                                                                                                                                                                                                                  
                code_Rpackage_available = `13. If the code is an R Package, and it was previously available on CRAN/Bioconductor (as stated in the Data Availability statement), is it still available? Check this by trying to install it on the most recent version of R. If you don't know how to do this/can't do this choose \"Unable to check\"`,
                code_OTHERpackage_available = `14. If the code is a package in another language (e.g. Python) published on PyPI please put the name of the package here and where it has been deposited we will see if it is still available. If you know how to look this up yourself, please do and mention whether it is still available here (Yes/No)`,
                code_application_cited = `18. APPLICATION papers only. How many times has the paper been cited? You can find this on the landing page of the paper.`,
                code_cited = `19. Has the code been cited (excluding the original paper it was archived for)? Code = the archived code (not the paper or package).`,
                code_citations = `20. If yes, how many times? (excluding the original paper it was archived for) Enter number or Unclear`,                                                                                                                                                                                                                                                    
                code_cited_notself = `21. Has the code been cited by someone other than the original authors?`,
                code_citations_notself = `22. If yes, how many times? Enter number or Unclear`,
                code_comments = `21. Do you have any other comments about the code? For example for those familiar with these processes, does the code use unit test? Doe it have continuous integration? Does it use docker/other containers?`,
                country_corresponding = `1. Country of corresponding author  (on spreadsheet)`,                                                                                                                                                                                                                                                                 
                country_first = `2. Country of first author. Use their main address on the paper. There may be more than one. We mean the address that is next to their name on the paper, NOT any “current address” that may be added for people who have recently moved institutions.`,                                                    
                georegion_data = `3. What georegion(s) were any novel data used in the paper collected from? Select all that apply. NOTE THIS MEANS DATA THAT WERE PHYSICALLY COLLECTED IN THESE COUNTRIES, DO NOT INCLUDE THINGS WHERE THE AUTHORS USED A DATASET FROM FRANCE BUT DID NOT ACTUALLY GO TO FRANCE TO COLLECT DATA :)`,         
                georegion_author_match = `4. Are any authors (use their main address on the paper) based in the georegion the data were collected from?  Also check the Acknowledgments to see if data labourers from the georegion who are not authors are mentioned there instead.`,
                georegion_data_cited = `17. For any paper(s) citing the data, what georegions are on the authors main addresses (i.e. when doing the work)? Please select all relevant options.`,                                                                                                                                                   
                equity_comments = `Any comments about data equity that these Qs don't cover?`,   
                comments = `2. Any other comments about this paper?`,                                                                                                                                                                                                                                                                   
                recorder = `1. Who recorded data from this paper? First name and initials only for GDPR reasons. If working in pairs, record both names separated by a comma.`, 
                issues = `1. Did you have any issues recording data for this paper? If yes we will go back and check it for you later.`) 

glimpse(raw_data_all)

naniar::miss_var_summary(raw_data_all)
naniar::vis_miss(clean_data_all)

# ------------------
# Issues to fix
# --------------------------------------------------------------------------
# Missing details that can easily be added using either paper number or DOI
# --------------------------------------------------------------------------
# Paper numbers
raw_data_all$paper_number[178] <- 1052
raw_data_all$paper_number[1761] <- 4113
raw_data_all$paper_number[1976] <- 2272

# DOIs
raw_data_all$doi[746] <- "10.1111/1365-2664.13326"
raw_data_all$doi[1109] <- "10.1111/1365-2664.14411"
raw_data_all$doi[1611] <- "10.1111/1365-2656.13994"
raw_data_all$doi[1627] <- "10.1111/1365-2656.12727"

# Journal names
raw_data_all$journal[190] <- "Methods in Ecology and Evolution"
raw_data_all$journal[246] <- "Journal of Ecology"
raw_data_all$journal[1628] <- "Methods in Ecology and Evolution"
raw_data_all$journal[1797] <- "Journal of Ecology"

# Article types
raw_data_all$article_type[556] <- "Research Article"
raw_data_all$article_type[600] <- "Research Article"
raw_data_all$article_type[1362] <- "Research Article"
raw_data_all$article_type[1384] <- "Research Article"
raw_data_all$article_type[1610] <- "Research Article"

# Row numbers 1001, 1246 = details all missing so exclude
raw_data_all <- raw_data_all %>% slice(c(-1001, -1246))

# --------------------------------------------------------------------------
# More complex fixes
# --------------------------------------------------------------------------
clean_data_all <-
  raw_data_all %>%
  # 1. Paper_number
  # Fix some typos
  mutate(paper_number = str_replace(paper_number, "32770", "3277")) %>%
  mutate(paper_number = str_replace(paper_number, "22272", "2272")) %>%
  # And return paper_number to numeric
  mutate(paper_number = as.numeric(paper_number)) %>%
  # 2. DOI
  # Some people used DOI, some used DOI link. Remove the links
  mutate(doi = str_replace_all(doi, "https://doi.org/", "")) %>%
  mutate(doi = str_replace_all(doi, "http://doi.org/", "")) %>%
  mutate(doi = str_replace_all(doi, "doi.org/", "")) %>%
  mutate(doi = str_replace_all(doi, "https://besjournals.onlinelibrary.wiley.com/doi/", "")) %>%
  # Someone pasted an ORCID, but other details match the paper number so swap for DOI
  mutate(doi = str_replace(doi, "https://orcid.org/0009-0008-2457-8954", "10.1111/1365-2656.13383")) %>%
  # 3. Journal
  # Fix one paper with incorrect journal name
  mutate(doi = str_replace(doi, "Ecology and Evolution", "Methods in Ecology and Evolution")) %>%
  # 4. Data used
  # Two papers have NA for data_used, but then go onto answer data questions so should be Yes
  mutate(data_used = replace_na(data_used, "Yes")) %>%
  # One paper incorrectly states that data was used, fix.
  mutate(data_used = case_when(paper_number == 1603 ~ "No",
                                       TRUE ~ as.character(data_used))) %>%
  # 5. Data mentioned in data availability statement
  # Several people forgot to answer this question. 
  # Checked and answered appropriately.
  mutate(data_availability = case_when(paper_number == 1897 ~ "Yes",
                                       paper_number == 245 ~ "Yes",
                                       paper_number == 346 ~ "Yes",
                                       paper_number == 1132 ~ "Yes",
                                       paper_number == 1595 ~ "Yes",
                                       TRUE ~ as.character(data_availability))) %>%
  # 6. Can you open the link? 
  # Some people have not answered this although data are mentioned in the data availability statement
  # Checked and answered appropriately.
  mutate(data_link = case_when(paper_number == 1003 ~ "Yes",
                                       paper_number == 1045 ~ "Yes",
                                       paper_number == 2697 ~ "Yes",
                                       paper_number == 1527 ~ "Yes",
                                       paper_number == 5561 ~ "Yes",
                                       paper_number == 2288 ~ "Yes",
                                       TRUE ~ as.character(data_link)))      
         
  
which(clean_data_all$data_availability == "Yes" & is.na(clean_data_all$data_archive))
sort(unique(clean_data_all$data_archive))


[1] "According to ethical requirements data is available only upon request to the authors."                                                                                                                                                                                                                                                                                                                                   
[2] "Apollo - University of Cambridge Repository"                                                                                                                                                                                                                                                                                                                                                                             
[3] "Arctic Data Center"                                                                                                                                                                                                                                                                                                                                                                                                      
[4] "Arctic Data Centre"                                                                                                                                                                                                                                                                                                                                                                                                      
[5] "As a list of citations to third-party data sources"                                                                                                                                                                                                                                                                                                                                                                      
[6] "Australian Antarctic Data Centre"                                                                                                                                                                                                                                                                                                                                                                                        
[7] "Australian National University Data Commons"                                                                                                                                                                                                                                                                                                                                                                             
[8] "CEFAS"                                                                                                                                                                                                                                                                                                                                                                                                                   
[9] "DANS"                                                                                                                                                                                                                                                                                                                                                                                                                    
[10] "DANS Data Station Life Sciences"                                                                                                                                                                                                                                                                                                                                                                                         
[11] "Data held by one author and the Missouri Department of Conservation"                                                                                                                                                                                                                                                                                                                                                     
[12] "Data is only available on request."                                                                                                                                                                                                                                                                                                                                                                                      
[13] "Data NOT archived because of twitter privacy terms."                                                                                                                                                                                                                                                                                                                                                                     
[14] "Data Repository of the University of Minnesota"                                                                                                                                                                                                                                                                                                                                                                          
[15] "data.4tu.nl"                                                                                                                                                                                                                                                                                                                                                                                                             
[16] "data.gov.uk"                                                                                                                                                                                                                                                                                                                                                                                                             
[17] "DataVerse"                                                                                                                                                                                                                                                                                                                                                                                                               
[18] "DataVerse;EDI Data Portal"                                                                                                                                                                                                                                                                                                                                                                                               
[19] "Digital.CSIC"                                                                                                                                                                                                                                                                                                                                                                                                            
[20] "Dryad"                                                                                                                                                                                                                                                                                                                                                                                                                   
[21] "Dryad;\"Trait data can be accessed through the TRY database: https://www.try-db.org (Kattge et al., 2020) and BIEN database: https://bien.nceas.ucsb.edu/bien/ (Enquist et al., 2016).\""                                                                                                                                                                                                                                
[22] "Dryad;and USGS"                                                                                                                                                                                                                                                                                                                                                                                                          
[23] "Dryad;CEFAS"                                                                                                                                                                                                                                                                                                                                                                                                             
[24] "Dryad;Czech Quaternary Palynological Database"                                                                                                                                                                                                                                                                                                                                                                           
[25] "Dryad;ENA"                                                                                                                                                                                                                                                                                                                                                                                                               
[26] "Dryad;Figshare"                                                                                                                                                                                                                                                                                                                                                                                                          
[27] "Dryad;GitHub, GitLab, Codeberg or similar platform"                                                                                                                                                                                                                                                                                                                                                                      
[28] "Dryad;GitHub, GitLab, Codeberg or similar platform;FlickR"                                                                                                                                                                                                                                                                                                                                                               
[29] "Dryad;GitHub, GitLab, Codeberg or similar platform;NCBI GenBank;Zenodo"                                                                                                                                                                                                                                                                                                                                                  
[30] "Dryad;GitHub, GitLab, Codeberg or similar platform;Zenodo"                                                                                                                                                                                                                                                                                                                                                               
[31] "Dryad;https://compadre-db.org/"                                                                                                                                                                                                                                                                                                                                                                                          
[32] "Dryad;https://datarepository.movebank.org/ and https://vigiechiro.herokuapp.com/"                                                                                                                                                                                                                                                                                                                                        
[33] "Dryad;Institutional repository"                                                                                                                                                                                                                                                                                                                                                                                          
[34] "Dryad;MoveBank"                                                                                                                                                                                                                                                                                                                                                                                                          
[35] "Dryad;MOVEBANK"                                                                                                                                                                                                                                                                                                                                                                                                          
[36] "Dryad;NCBI GenBank"                                                                                                                                                                                                                                                                                                                                                                                                      
[37] "Dryad;NCBI GenBank;Arctos"                                                                                                                                                                                                                                                                                                                                                                                               
[38] "Dryad;NCBI GenBank;Supplementary materials"                                                                                                                                                                                                                                                                                                                                                                              
[39] "Dryad;Only part of the data (that were uploaded on DRYAD) can be accessed. The data availability statement points to another source: LOng-Term Vegetation Sampling database https://lotvs.csic.es/ and is partially restricted."                                                                                                                                                                                         
[40] "Dryad;Personal website;forestplots.net"                                                                                                                                                                                                                                                                                                                                                                                  
[41] "Dryad;sequence data are archived in the MG-RAST public database (Project ID: 4745987.3)"                                                                                                                                                                                                                                                                                                                                 
[42] "Dryad;Supplementary materials"                                                                                                                                                                                                                                                                                                                                                                                           
[43] "Dryad;TRY Database"                                                                                                                                                                                                                                                                                                                                                                                                      
[44] "Dryad;TRY database, Dataset 416"                                                                                                                                                                                                                                                                                                                                                                                         
[45] "Dryad;website on publication"                                                                                                                                                                                                                                                                                                                                                                                            
[46] "Dryad;World Spider Trait Databasde"                                                                                                                                                                                                                                                                                                                                                                                      
[47] "Dryad;Zenodo"                                                                                                                                                                                                                                                                                                                                                                                                            
[48] "Ecological Archives"                                                                                                                                                                                                                                                                                                                                                                                                     
[49] "EDI Data Portal"                                                                                                                                                                                                                                                                                                                                                                                                         
[50] "EDI Repository"                                                                                                                                                                                                                                                                                                                                                                                                          
[51] "edi repository and Bonanza Creek LTER web page"                                                                                                                                                                                                                                                                                                                                                                          
[52] "Edinburgh DataShare"                                                                                                                                                                                                                                                                                                                                                                                                     
[53] "EDMOND Digital Repository"                                                                                                                                                                                                                                                                                                                                                                                               
[54] "envidat.ch data portal of the Swiss Federal Institute for Forest, Snow and Landscape Research WSL"                                                                                                                                                                                                                                                                                                                       
[55] "Environmental Data Initiative"                                                                                                                                                                                                                                                                                                                                                                                           
[56] "Environmental Data Initiative (EDI Data Portal)"                                                                                                                                                                                                                                                                                                                                                                         
[57] "Environmental Data Initiative (EDI) Data Portal"                                                                                                                                                                                                                                                                                                                                                                         
[58] "Environmental Data Initiative (https://portal.edirepository.org/nis/home.jsp)"                                                                                                                                                                                                                                                                                                                                           
[59] "Environmental Data Initiative and Kellogg Biological Station LTER website (deposited here as required by the Funding)"                                                                                                                                                                                                                                                                                                   
[60] "erda.dk"                                                                                                                                                                                                                                                                                                                                                                                                                 
[61] "Etsin"                                                                                                                                                                                                                                                                                                                                                                                                                   
[62] "Figshare"                                                                                                                                                                                                                                                                                                                                                                                                                
[63] "Figshare;FUNdiv"                                                                                                                                                                                                                                                                                                                                                                                                         
[64] "Figshare;GitHub, GitLab, Codeberg or similar platform"                                                                                                                                                                                                                                                                                                                                                                   
[65] "Figshare;GitHub, GitLab, Codeberg or similar platform;Authors used data form a published study archived on Figshare. They also simulated some data for one of the result figures and archived it on Github"                                                                                                                                                                                                              
[66] "Figshare;https://archive.org/"                                                                                                                                                                                                                                                                                                                                                                                           
[67] "Figshare;Institutional repository"                                                                                                                                                                                                                                                                                                                                                                                       
[68] "Figshare;Institutional repository;They refer to it as the institutional repository but it is a Figshare wrapper."                                                                                                                                                                                                                                                                                                        
[69] "Figshare;Movebank"                                                                                                                                                                                                                                                                                                                                                                                                       
[70] "Figshare;NCBI GenBank"                                                                                                                                                                                                                                                                                                                                                                                                   
[71] "Figshare;Supplementary materials"                                                                                                                                                                                                                                                                                                                                                                                        
[72] "Figure 3 in the methods section, and the immediaately proceeding paragraph."                                                                                                                                                                                                                                                                                                                                             
[73] "Forest Plots"                                                                                                                                                                                                                                                                                                                                                                                                            
[74] "From other cited documents, but not findable in Google Scholar. So no access to data."                                                                                                                                                                                                                                                                                                                                   
[75] "GBIF"                                                                                                                                                                                                                                                                                                                                                                                                                    
[76] "GBIF;Zenodo"                                                                                                                                                                                                                                                                                                                                                                                                             
[77] "GitHub, GitLab, Codeberg or similar platform"                                                                                                                                                                                                                                                                                                                                                                            
[78] "GitHub, GitLab, Codeberg or similar platform;CRAN"                                                                                                                                                                                                                                                                                                                                                                       
[79] "GitHub, GitLab, Codeberg or similar platform;Cran; data is part of an r-packge."                                                                                                                                                                                                                                                                                                                                         
[80] "GitHub, GitLab, Codeberg or similar platform;Institutional repository"                                                                                                                                                                                                                                                                                                                                                   
[81] "GitHub, GitLab, Codeberg or similar platform;Knowledge Network for Biocomplexity"                                                                                                                                                                                                                                                                                                                                        
[82] "GitHub, GitLab, Codeberg or similar platform;Supplementary materials;Zenodo;The authors have the data saved in the supplementary material. This is archived in GitHub and one of the versions is archived in Zenodo."                                                                                                                                                                                                    
[83] "GitHub, GitLab, Codeberg or similar platform;Zenodo"                                                                                                                                                                                                                                                                                                                                                                     
[84] "GitHub, GitLab, Codeberg or similar platform;Zenodo;R CRAN"                                                                                                                                                                                                                                                                                                                                                              
[85] "GitHub, GitLab, Codeberg or similar platform;Zenodo;R package on CRAN"                                                                                                                                                                                                                                                                                                                                                   
[86] "Government repository (National Science Foundation Arctic Data Center)"                                                                                                                                                                                                                                                                                                                                                  
[87] "Government repository (USGS)"                                                                                                                                                                                                                                                                                                                                                                                            
[88] "Griffith University and Walalakoo Aboriginal Corporation"                                                                                                                                                                                                                                                                                                                                                                
[89] "Harvard Dataverse"                                                                                                                                                                                                                                                                                                                                                                                                       
[90] "https://data.botanik.uni-halle.de/bef-china/datasets/655"                                                                                                                                                                                                                                                                                                                                                                
[91] "https://data.neotomadb.or"                                                                                                                                                                                                                                                                                                                                                                                               
[92] "https://ged.ofb.fr"                                                                                                                                                                                                                                                                                                                                                                                                      
[93] "https://radar.brookes.ac.uk/"                                                                                                                                                                                                                                                                                                                                                                                            
[94] "https://researchdata.se/"                                                                                                                                                                                                                                                                                                                                                                                                
[95] "https://www.bco-dmo.org/dataset/639335"                                                                                                                                                                                                                                                                                                                                                                                  
[96] "Illinois Data Bank (https://databank.illinois.edu/)"                                                                                                                                                                                                                                                                                                                                                                     
[97] "IMIS - the Integrated Marine Information System https://www.vliz.be/en/imis"                                                                                                                                                                                                                                                                                                                                             
[98] "In the manuscript"                                                                                                                                                                                                                                                                                                                                                                                                       
[99] "In the paper itself"                                                                                                                                                                                                                                                                                                                                                                                                     
[100] "INRAE - French government"                                                                                                                                                                                                                                                                                                                                                                                               
[101] "Institutional repository"                                                                                                                                                                                                                                                                                                                                                                                                
[102] "Institutional repository;4TU.ResearchData"                                                                                                                                                                                                                                                                                                                                                                               
[103] "Institutional repository;Environmental Data Initiative"                                                                                                                                                                                                                                                                                                                                                                  
[104] "Institutional repository;European Tracking Network (ETN) database (https://lifewatch.be/etn)"                                                                                                                                                                                                                                                                                                                            
[105] "Institutional repository;Government databases."                                                                                                                                                                                                                                                                                                                                                                          
[106] "Institutional repository;https://datastore.landcareresearch.co.nz"                                                                                                                                                                                                                                                                                                                                                       
[107] "Institutional repository;https://dataverse.nl"                                                                                                                                                                                                                                                                                                                                                                           
[108] "Institutional repository;Linked to another journal"                                                                                                                                                                                                                                                                                                                                                                      
[109] "Institutional repository;MassIVE, ProteomeXchange"                                                                                                                                                                                                                                                                                                                                                                       
[110] "Institutional repository;NCBI GenBank"                                                                                                                                                                                                                                                                                                                                                                                   
[111] "Institutional repository;Official archive of publicly accessible USGS source code (https://code.usgs.gov/usgs)"                                                                                                                                                                                                                                                                                                          
[112] "Institutional repository;Research Data Australia (RDA) online portal"                                                                                                                                                                                                                                                                                                                                                    
[113] "Institutional repository;Supplementary materials"                                                                                                                                                                                                                                                                                                                                                                        
[114] "International Tree-Ring Data Bank"                                                                                                                                                                                                                                                                                                                                                                                       
[115] "It is a metaanalysis, point interested readers to the list of revised papers"                                                                                                                                                                                                                                                                                                                                            
[116] "Kenyan STR profiles are unshareable."                                                                                                                                                                                                                                                                                                                                                                                    
[117] "KNB (The Knowledge Network for Biocomplexity, https://knb.ecoinformatics.org/)"                                                                                                                                                                                                                                                                                                                                          
[118] "Knowledge Network for Biocomplexity"                                                                                                                                                                                                                                                                                                                                                                                     
[119] "Knowledge Network for Biocomplexity (KNB)"                                                                                                                                                                                                                                                                                                                                                                               
[120] "Knowledge Network for Biocomplexity (KNB) repository"                                                                                                                                                                                                                                                                                                                                                                    
[121] "Labeled Information Library of Alexandria: Biology and Conservation"                                                                                                                                                                                                                                                                                                                                                     
[122] "Lancaster University"                                                                                                                                                                                                                                                                                                                                                                                                    
[123] "mandeley"                                                                                                                                                                                                                                                                                                                                                                                                                
[124] "Mendeley"                                                                                                                                                                                                                                                                                                                                                                                                                
[125] "Mendeley Data"                                                                                                                                                                                                                                                                                                                                                                                                           
[126] "MendeleyData"                                                                                                                                                                                                                                                                                                                                                                                                            
[127] "Mendely Data"                                                                                                                                                                                                                                                                                                                                                                                                            
[128] "Metabolights"                                                                                                                                                                                                                                                                                                                                                                                                            
[129] "Metacat Data Catalog"                                                                                                                                                                                                                                                                                                                                                                                                    
[130] "metagenomics RAST server"                                                                                                                                                                                                                                                                                                                                                                                                
[131] "MoveBank"                                                                                                                                                                                                                                                                                                                                                                                                                
[132] "Movebank and the r package ‘moveVis’"                                                                                                                                                                                                                                                                                                                                                                                    
[133] "MyDiv"                                                                                                                                                                                                                                                                                                                                                                                                                   
[134] "National Tibetan Plateau Data Center"                                                                                                                                                                                                                                                                                                                                                                                    
[135] "NCBI"                                                                                                                                                                                                                                                                                                                                                                                                                    
[136] "NCBI GenBank"                                                                                                                                                                                                                                                                                                                                                                                                            
[137] "NCBI GenBank;Environmental Information Data Centre"                                                                                                                                                                                                                                                                                                                                                                      
[138] "NCBI GenBank;PlutoF"                                                                                                                                                                                                                                                                                                                                                                                                     
[139] "NCBI SRA"                                                                                                                                                                                                                                                                                                                                                                                                                
[140] "NCBI SRA database"                                                                                                                                                                                                                                                                                                                                                                                                       
[141] "Neotoma Paleoecology Database"                                                                                                                                                                                                                                                                                                                                                                                           
[142] "NERC EIDC"                                                                                                                                                                                                                                                                                                                                                                                                               
[143] "NERC Environmental Information Data Centre"                                                                                                                                                                                                                                                                                                                                                                              
[144] "nowhere"                                                                                                                                                                                                                                                                                                                                                                                                                 
[145] "NSF Arctic Data Center"                                                                                                                                                                                                                                                                                                                                                                                                  
[146] "OFD (Office Français de la Biodiversité"                                                                                                                                                                                                                                                                                                                                                                                 
[147] "On request"                                                                                                                                                                                                                                                                                                                                                                                                              
[148] "OSF (https://osf.io/)"                                                                                                                                                                                                                                                                                                                                                                                                   
[149] "Oxford Research Archive"                                                                                                                                                                                                                                                                                                                                                                                                 
[150] "pangaea"                                                                                                                                                                                                                                                                                                                                                                                                                 
[151] "PANGAEA"                                                                                                                                                                                                                                                                                                                                                                                                                 
[152] "Pangaea repository"                                                                                                                                                                                                                                                                                                                                                                                                      
[153] "PANGAEA."                                                                                                                                                                                                                                                                                                                                                                                                                
[154] "Personal website"                                                                                                                                                                                                                                                                                                                                                                                                        
[155] "Purdue University Research Repository"                                                                                                                                                                                                                                                                                                                                                                                   
[156] "R script on ARP Adatrepozitorium"                                                                                                                                                                                                                                                                                                                                                                                        
[157] "researchdata.gla.ac.uk"                                                                                                                                                                                                                                                                                                                                                                                                  
[158] "researchdata.se"                                                                                                                                                                                                                                                                                                                                                                                                         
[159] "Researchdata.se"                                                                                                                                                                                                                                                                                                                                                                                                         
[160] "ScienceBase"                                                                                                                                                                                                                                                                                                                                                                                                             
[161] "sciencebase.gov"                                                                                                                                                                                                                                                                                                                                                                                                         
[162] "Senckenberg (meta)data portal"                                                                                                                                                                                                                                                                                                                                                                                           
[163] "Sequence Read Archive (SRA)"                                                                                                                                                                                                                                                                                                                                                                                             
[164] "Smithsonian"                                                                                                                                                                                                                                                                                                                                                                                                             
[165] "Some are available on Research Data Repository of the Research Collection of ETH Zürich, others are available on request"                                                                                                                                                                                                                                                                                                
[166] "Supplementary materials"                                                                                                                                                                                                                                                                                                                                                                                                 
[167] "Supplementary materials;ESS-DIVE, Google Earth Engine. Links are included in Supplementary Material 4"                                                                                                                                                                                                                                                                                                                   
[168] "Supplementary materials;Mendeley Data Repository"                                                                                                                                                                                                                                                                                                                                                                        
[169] "Supplementary materials;Zenodo"                                                                                                                                                                                                                                                                                                                                                                                          
[170] "The aphid and plankton data used for this study can be obtained after getting permission from the data owners, the Rothamsted Insect Survey and the Sir Alister Hardy Foundation for Ocean Science, which is part of the Marine Biological Association of the UK. Chlorophyll data from the California current were processed from https://coastwatch.pfeg.noaa.gov/erddap/tabledap/index.html?page=1&itemsPerPage=1000."
[171] "The data is archived here but I can't open the link: https://doi:10.5061/dryad.vk002fn"                                                                                                                                                                                                                                                                                                                                  
[172] "the Harvard Dataverse repository"                                                                                                                                                                                                                                                                                                                                                                                        
[173] "U.S. Geological Survey Data Release."                                                                                                                                                                                                                                                                                                                                                                                    
[174] "United States Geological Survey (USGS)"                                                                                                                                                                                                                                                                                                                                                                                  
[175] "University (but not available)"                                                                                                                                                                                                                                                                                                                                                                                          
[176] "University of Illinois databank"                                                                                                                                                                                                                                                                                                                                                                                         
[177] "University of Vienna"                                                                                                                                                                                                                                                                                                                                                                                                    
[178] "USGS"                                                                                                                                                                                                                                                                                                                                                                                                                    
[179] "USGS Science Base"                                                                                                                                                                                                                                                                                                                                                                                                       
[180] "USGS ScienceBase"                                                                                                                                                                                                                                                                                                                                                                                                        
[181] "USGS ScienceBase online data repository platform"                                                                                                                                                                                                                                                                                                                                                                        
[182] "USGS ScienceBase website and digital repository"                                                                                                                                                                                                                                                                                                                                                                         
[183] "Zenodo"                                                                                                                                                                                                                                                                                                                                                                                                                  
[184] "Zenodo;DOI not found"                                                                                                                                                                                                                                                                                                                                                                                                    
[185] "Zenodo;EMBL-EBI"                                                                                                                                                                                                                                                                                                                                                                                                         
[186] "Zenodo;Google Earth Engine"                                                                                                                                                                                                                                                                                                                                                                                              
[187] "Zenodo;https://www.fs.usda.gov/rds/archive/Catalog/RDS-2015-0010"                                                                                                                                                                                                                                                                                                                                                        
[188] "Zenodo;Pangea"                                                                                                                                                                                                                                                                                                                                                                                                           
[189] "Zenodo;Phenology Observation Portal"                                                                                                                                                                                                                                                                                                                                                                                     
[190] "Zenodo;R Cran"                                                                                                                                                                                                                                                                                                                                                                                                           
[191] "ziva hub"                                                                                                                                                                                                                                                                                                                                                                                                                
[192] "ZivaHub"      



# Data validation 2272

dat_valid <- filter(raw_data_questions, paper_number == 2272)
